/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainapp;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    public dbAccess db = new dbAccess();
    public GlobalVariabel gv = new GlobalVariabel();
    private TambahData TD = new TambahData();
    private UbahData UD = new UbahData();
    private Tentang TT = new Tentang();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        initLevel0();
        initLevel1();
        initLevel2();
        initLevel3();
        initLevel4();
    }
    
    private void initLevel0(){
        setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon-x16.png")));
    }
    
    private void initLevel1(){
        buttonProverty();
    }
    
    private void initLevel2(){
        db.showDataSiswa();
    }
    
    private void initLevel3(){
        TableColumnModel ts = tabelSiswa.getColumnModel();
        ts.getColumn(0).setPreferredWidth(2);
        ts.getColumn(1).setPreferredWidth(98);
        ts.getColumn(2).setPreferredWidth(98);
        ts.getColumn(3).setPreferredWidth(98);
        
        TableCellRenderer rendererFromHeader = tabelSiswa.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        
        tabelSiswa.getTableHeader().setOpaque(false);
        tabelSiswa.getTableHeader().setBackground(Color.decode("#3399FF"));
        tabelSiswa.getTableHeader().setForeground(Color.WHITE);
    }
    
    private void initLevel4(){
        addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        if (JOptionPane.showConfirmDialog(null, 
            "Apakah Anda ingin keluar dari Aplikasi?", "Konfirmasi keluar", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
            }
    }
        });
    }
    
    private void buttonProverty(){
        if(gv.ButtonProverty == 0){
            btnUbahData.setEnabled(false);
            btnHapusData.setEnabled(false);
        }
        else{
            btnUbahData.setEnabled(true);
            btnHapusData.setEnabled(true);
        }
    }

    public void updateTables(){
        db.showDataSiswa();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSiswa = new javax.swing.JTable();
        btnTambahData = new javax.swing.JButton();
        btnHapusData = new javax.swing.JButton();
        btnUbahData = new javax.swing.JButton();
        btnRefreshTabel = new javax.swing.JButton();
        btnEksporData = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Manajemen Data Siswa");
        setResizable(false);

        tabelSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "No", "NISN", "Nama Siswa", "Kelas dan Jurusan"
            }
        ));
        tabelSiswa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tabelSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelSiswa.setRowMargin(5);
        tabelSiswa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelSiswa.getTableHeader().setReorderingAllowed(false);
        tabelSiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabelSiswaFocusGained(evt);
            }
        });
        tabelSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSiswa);

        btnTambahData.setText("Tambah Data");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });

        btnHapusData.setText("Hapus Data");
        btnHapusData.setEnabled(false);
        btnHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDataActionPerformed(evt);
            }
        });

        btnUbahData.setText("Ubah Data");
        btnUbahData.setEnabled(false);
        btnUbahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahDataActionPerformed(evt);
            }
        });

        btnRefreshTabel.setText("Refresh Tabel");
        btnRefreshTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTabelActionPerformed(evt);
            }
        });

        btnEksporData.setText("Ekspor Data");
        btnEksporData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporDataActionPerformed(evt);
            }
        });

        btnReset.setText("Setel Ulang");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButton1.setText("i");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambahData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshTabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEksporData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbahData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusData)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahData)
                    .addComponent(btnHapusData)
                    .addComponent(btnUbahData)
                    .addComponent(btnRefreshTabel)
                    .addComponent(btnEksporData)
                    .addComponent(btnReset)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
        TD.setVisible(false);
        TD.setVisible(true);
        TD.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void btnUbahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahDataActionPerformed
        UD.setVisible(false);
        UD.setVisible(true);
        UD.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnUbahDataActionPerformed

    private void tabelSiswaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelSiswaFocusGained

    }//GEN-LAST:event_tabelSiswaFocusGained

    private void tabelSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSiswaMouseClicked
        gv.NISNSiswa = tabelSiswa.getValueAt(tabelSiswa.getSelectedRow(), 1).toString();
        db.selectDataSiswa();
        gv.ButtonProverty = 1;
        buttonProverty();
    }//GEN-LAST:event_tabelSiswaMouseClicked

    private void btnHapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDataActionPerformed
        if(gv.singleInstance < 1){
            gv.singleInstance = 1;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Yakin ingin menghapus data ini?","Perhatian",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                db.deleteDataSiswa();
                gv.singleInstance = 0;
            }
        }
    }//GEN-LAST:event_btnHapusDataActionPerformed

    private void btnRefreshTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTabelActionPerformed
        db.showDataSiswa();
    }//GEN-LAST:event_btnRefreshTabelActionPerformed

    private void btnEksporDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporDataActionPerformed
        if(gv.singleInstance < 1){
            gv.singleInstance = 1;
            try {
                db.exportDataSiswa();
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEksporDataActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        if(gv.singleInstance < 1){
            gv.singleInstance = 1;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Yakin ingin menyetel ulang data siswa? Seluruh data akan terhapus","Perhatian",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                db.resetDataSiswa();
                gv.singleInstance = 0;
            }
            else{
                gv.singleInstance = 0;
            }
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TT.setVisible(false);
        TT.setVisible(true);
        TT.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEksporData;
    public static javax.swing.JButton btnHapusData;
    private javax.swing.JButton btnRefreshTabel;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambahData;
    public static javax.swing.JButton btnUbahData;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabelSiswa;
    // End of variables declaration//GEN-END:variables
}
